# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'objave',
            },
        ),
    ]
