# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-08-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
        migrations.AddField(
            model_name='publication',
            name='subtitle',
            field=models.TextField(default='subtitle', max_length=200),
            preserve_default=False,
        ),
    ]
